"""
sanctions_screening.py — Sanctions / PEP screening.

Loads from sanctions_data.json (generated by sanctions_loader.py) when
available. Falls back to the illustrative seed lists if the file is absent.

To refresh real data:
    python risk_engine/sanctions_loader.py --output risk_engine/sanctions_data.json

Real sources:
  OFAC SDN:  https://www.treasury.gov/ofac/downloads/sdn.csv
  UN SC:     https://scsanctions.un.org/resources/xml/en/consolidated.xml
  RBI UAPA:  https://www.rbi.org.in (static seed in sanctions_loader.py)
"""
import os, json

_HERE = os.path.dirname(__file__)
_DATA_FILE = os.path.join(_HERE, "sanctions_data.json")

# ── Illustrative fallback seeds ───────────────────────────────────────
_SANCTIONS_SEED = [
    "Example Sanctioned Entity Alpha",
    "Example Sanctioned Person Beta",
    "Fictional Shell Company Gamma Trading",
]
_PEP_SEED = [
    "Example Former Minister Delta",
    "Example State Official Epsilon",
]

def _load_lists():
    if os.path.exists(_DATA_FILE):
        with open(_DATA_FILE) as f:
            data = json.load(f)
        sanctions = data.get("sanctions", [])
        pep       = data.get("pep", [])
        source    = f"sanctions_data.json ({data.get('counts',{}).get('total_unique',0)} entries, generated {data.get('generated_at','unknown')})"
        is_real   = True
    else:
        sanctions = _SANCTIONS_SEED
        pep       = _PEP_SEED
        source    = "illustrative seed lists — run sanctions_loader.py to fetch real data"
        is_real   = False
    return sanctions, pep, source, is_real

_SANCTIONS, _PEP, _SOURCE, _IS_REAL = _load_lists()

def _norm(name: str) -> str:
    return " ".join(name.lower().split())

def check_sanctions(payee_name: str, threshold: float = 0.85) -> dict:
    from rapidfuzz import fuzz
    norm = _norm(payee_name)

    best_s = {"score": 0.0, "matched": None}
    best_p = {"score": 0.0, "matched": None}

    for entry in _SANCTIONS:
        sc = fuzz.token_sort_ratio(norm, _norm(entry)) / 100
        if sc > best_s["score"]:
            best_s = {"score": sc, "matched": entry}

    for entry in _PEP:
        sc = fuzz.token_sort_ratio(norm, _norm(entry)) / 100
        if sc > best_p["score"]:
            best_p = {"score": sc, "matched": entry}

    s_hit = best_s["score"] >= threshold
    p_hit = best_p["score"] >= threshold

    if s_hit:
        flag   = "sanctions_match"
        reason = f"{best_s['score']:.0%} match: {best_s['matched']}"
    elif p_hit:
        flag   = "pep_match"
        reason = f"{best_p['score']:.0%} PEP match: {best_p['matched']}"
    else:
        flag   = "clear"
        reason = "No match above threshold"

    return {
        "flag": flag, "reason": reason,
        "sanctions_score": round(best_s["score"], 2),
        "pep_score":       round(best_p["score"], 2),
        "algorithm":       "fuzzy_token_sort",
        "data_source":     _SOURCE,
        "using_real_data": _IS_REAL,
    }

if __name__ == "__main__":
    print("Source:", _SOURCE)
    print("Real data:", _IS_REAL)
    print(check_sanctions("Lashkar-e-Taiba"))
    print(check_sanctions("Suresh Kumar"))
